use serde::{Deserialize, Deserializer, Serialize, Serializer};

use crate::session::extension_data::ExtensionState;

pub const DEFAULT_AUTO_COMPACT_THRESHOLD: f64 = 0.8;
pub const CURRENT_CONTEXT_RUNTIME_SCHEMA_VERSION: u32 = 6;
pub(crate) const DEFAULT_STAGE_THRESHOLD: f64 = 0.65;
pub const CONTEXT_RUNTIME_OUTPUT_RESERVE_TOKENS: usize = 8_000;
pub(crate) const STAGE_HEADROOM_BUFFER_TOKENS: usize = 26_000;
pub(crate) const COMMIT_HEADROOM_BUFFER_TOKENS: usize = 18_000;
pub(crate) const AUTO_HEADROOM_BUFFER_TOKENS: usize = 13_000;
pub(crate) const STAGE_ABSOLUTE_TRIGGER_TOKENS: usize = 8_000;
pub(crate) const COMMIT_ABSOLUTE_TRIGGER_TOKENS: usize = 12_000;
pub(crate) const AUTO_ABSOLUTE_TRIGGER_TOKENS: usize = 18_000;
pub(crate) const STAGE_KEEP_FIRST_MESSAGES: usize = 2;
pub(crate) const STAGE_KEEP_LAST_MESSAGES: usize = 8;
pub(crate) const HEAVY_STAGE_KEEP_LAST_MESSAGES: usize = 2;
pub(crate) const MIN_MESSAGES_TO_STAGE: usize = 24;
pub(crate) const MIN_HEAVY_MESSAGES_TO_STAGE: usize = 5;
pub(crate) const SNIP_KEEP_RECENT_MESSAGES: usize = 24;
pub(crate) const SNIP_MAX_REMOVALS: usize = 64;
pub(crate) const MICROCOMPACT_KEEP_RECENT_MESSAGES: usize = 12;
pub(crate) const MICROCOMPACT_MIN_TEXT_CHARS: usize = 1_000;
pub(crate) const MICROCOMPACT_MAX_ENTRIES: usize = 24;
pub(crate) const TIME_BASED_MICROCOMPACT_GAP_SECS: i64 = 60 * 60;
pub(crate) const TIME_BASED_MICROCOMPACT_KEEP_RECENT_RESULTS: usize = 5;
pub(crate) const AUTO_SESSION_MEMORY_MIN_TOKENS: usize = 10_000;
pub(crate) const AUTO_SESSION_MEMORY_MIN_TEXT_MESSAGES: usize = 5;
pub(crate) const AUTO_SESSION_MEMORY_MAX_TOKENS: usize = 40_000;
pub(crate) const MANUAL_SESSION_MEMORY_MIN_TOKENS: usize = 3_000;
pub(crate) const MANUAL_SESSION_MEMORY_MIN_TEXT_MESSAGES: usize = 2;
pub(crate) const MANUAL_SESSION_MEMORY_MAX_TOKENS: usize = 20_000;
pub(crate) const OVERFLOW_SESSION_MEMORY_MIN_TOKENS: usize = 6_000;
pub(crate) const OVERFLOW_SESSION_MEMORY_MIN_TEXT_MESSAGES: usize = 3;
pub(crate) const OVERFLOW_SESSION_MEMORY_MAX_TOKENS: usize = 32_000;
pub(crate) const TOOL_REQUEST_ARG_CHAR_LIMIT: usize = 1200;
pub(crate) const TOOL_RESPONSE_TEXT_CHAR_LIMIT: usize = 2000;
pub(crate) const CONTEXT_RUNTIME_CONTINUATION_TEXT: &str =
    "The previous message contains preserved context generated by the runtime context system. \
Continue naturally using that context. Do not mention summarization, collapse, or compression.";

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct CompactBoundaryMetadata {
    pub anchor_index: usize,
    pub head_index: usize,
    pub tail_index: usize,
    #[serde(default)]
    pub direction: CompactDirection,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub anchor_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub head_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tail_message_id: Option<String>,
    pub created_at: i64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CompactDirection {
    #[default]
    UpTo,
    From,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CollapseCommit {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit_id: Option<String>,
    pub summary: String,
    pub start_index: usize,
    pub end_index: usize,
    #[serde(default)]
    pub direction: CompactDirection,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_message_id: Option<String>,
    pub created_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CollapseSnapshot {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub snapshot_id: Option<String>,
    pub start_index: usize,
    pub end_index: usize,
    #[serde(default)]
    pub direction: CompactDirection,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_message_id: Option<String>,
    pub summary: String,
    pub risk: f64,
    pub staged_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SessionMemoryState {
    pub summary: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub summarized_through_message_id: Option<String>,
    pub preserved_start_index: usize,
    pub preserved_end_index: usize,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preserved_start_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preserved_end_message_id: Option<String>,
    pub preserved_message_count: usize,
    pub preserved_token_estimate: usize,
    pub tail_anchor_index: usize,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tail_anchor_message_id: Option<String>,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SnipRemovalState {
    pub removed_indexes: Vec<usize>,
    #[serde(default)]
    pub removed_message_ids: Vec<String>,
    pub removed_count: usize,
    pub token_estimate_freed: usize,
    pub reason: String,
    pub created_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum MicrocompactMode {
    #[default]
    MarkerRewrite,
    Cached,
    TimeBased,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MicrocompactState {
    pub message_index: usize,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
    pub tool_response_ids: Vec<String>,
    #[serde(default)]
    pub mode: MicrocompactMode,
    pub original_text_chars: usize,
    pub original_text_lines: usize,
    pub compacted_text_chars: usize,
    pub compacted_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PreservedSegmentMetadata {
    pub start_index: usize,
    pub end_index: usize,
    pub tail_anchor_index: usize,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_message_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tail_anchor_message_id: Option<String>,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ProjectionStats {
    pub base_agent_messages: usize,
    pub projected_agent_messages: usize,
    pub snip_removed_count: usize,
    pub microcompacted_count: usize,
    pub raw_token_estimate: usize,
    pub projected_token_estimate: usize,
    pub freed_token_estimate: usize,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PostCompactValidation {
    pub compact_kind: String,
    pub reason: String,
    pub before_projected_tokens: usize,
    pub after_projected_tokens: usize,
    pub threshold_tokens: usize,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retained_start_index: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub retained_end_index: Option<usize>,
    pub cleanup_triggered: bool,
    pub still_over_threshold: bool,
    pub validated_at: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContextRuntimeStore {
    #[serde(default)]
    pub entry_log: Vec<ContextRuntimeStoreEntry>,
    #[serde(default)]
    pub collapse_commits: Vec<CollapseCommit>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub staged_snapshot: Option<CollapseSnapshot>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_memory: Option<SessionMemoryState>,
    #[serde(default)]
    pub snip_entries: Vec<SnipRemovalState>,
    #[serde(default)]
    pub microcompact_entries: Vec<MicrocompactState>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preserved_segment: Option<PreservedSegmentMetadata>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub boundary: Option<CompactBoundaryMetadata>,
}

impl ContextRuntimeStore {
    pub fn is_empty(&self) -> bool {
        self.entry_log.is_empty()
            && self.collapse_commits.is_empty()
            && self.staged_snapshot.is_none()
            && self.session_memory.is_none()
            && self.snip_entries.is_empty()
            && self.microcompact_entries.is_empty()
            && self.preserved_segment.is_none()
            && self.boundary.is_none()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ContextRuntimeStoreEntry {
    StagedSnapshotSet {
        snapshot: CollapseSnapshot,
    },
    StagedSnapshotCleared,
    CollapseCommitAdded {
        commit: CollapseCommit,
    },
    CollapseCommitsCleared,
    SessionMemorySet {
        #[serde(rename = "sessionMemory")]
        session_memory: SessionMemoryState,
    },
    SessionMemoryCleared,
    SnipEntriesSet {
        entries: Vec<SnipRemovalState>,
    },
    SnipEntriesCleared,
    MicrocompactEntriesSet {
        entries: Vec<MicrocompactState>,
    },
    MicrocompactEntriesCleared,
    BoundarySet {
        boundary: CompactBoundaryMetadata,
    },
    BoundaryCleared,
    PreservedSegmentSet {
        preserved_segment: PreservedSegmentMetadata,
    },
    PreservedSegmentCleared,
}

#[derive(Debug, Clone, Serialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ContextRuntimeStateSummary {
    pub schema_version: u32,
    pub runtime_compactions: u32,
    pub committed_collapse_count: usize,
    pub staged_collapse_count: usize,
    pub snip_removed_count: usize,
    pub microcompacted_count: usize,
    pub session_memory_active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preserved_segment: Option<PreservedSegmentMetadata>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compact_boundary: Option<CompactBoundaryMetadata>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_projection_stats: Option<ProjectionStats>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_compact_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_recovery_result: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_post_compact_validation: Option<PostCompactValidation>,
}

#[derive(Debug, Clone)]
pub struct ContextRuntimeState {
    pub schema_version: u32,
    pub store: ContextRuntimeStore,
    pub runtime_compactions: u32,
    pub last_projection_stats: Option<ProjectionStats>,
    pub last_compact_reason: Option<String>,
    pub last_recovery_result: Option<String>,
    pub last_post_compact_validation: Option<PostCompactValidation>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ContextRuntimeStateSerializeWire<'a> {
    schema_version: u32,
    #[serde(default, skip_serializing_if = "ContextRuntimeStore::is_empty")]
    store: &'a ContextRuntimeStore,
    #[serde(default)]
    runtime_compactions: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    last_projection_stats: &'a Option<ProjectionStats>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    last_compact_reason: &'a Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    last_recovery_result: &'a Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    last_post_compact_validation: &'a Option<PostCompactValidation>,
}

impl Default for ContextRuntimeState {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_CONTEXT_RUNTIME_SCHEMA_VERSION,
            store: ContextRuntimeStore::default(),
            runtime_compactions: 0,
            last_projection_stats: None,
            last_compact_reason: None,
            last_recovery_result: None,
            last_post_compact_validation: None,
        }
    }
}

impl Serialize for ContextRuntimeState {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let restored = self.restored_from_entry_log();
        ContextRuntimeStateSerializeWire {
            schema_version: CURRENT_CONTEXT_RUNTIME_SCHEMA_VERSION,
            store: &restored.store,
            runtime_compactions: restored.runtime_compactions,
            last_projection_stats: &restored.last_projection_stats,
            last_compact_reason: &restored.last_compact_reason,
            last_recovery_result: &restored.last_recovery_result,
            last_post_compact_validation: &restored.last_post_compact_validation,
        }
        .serialize(serializer)
    }
}

#[derive(Debug, Clone, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
struct LegacyContextRuntimeStateWire {
    #[serde(default)]
    schema_version: Option<u32>,
    #[serde(default)]
    store: Option<ContextRuntimeStore>,
    #[serde(default)]
    runtime_compactions: u32,
    #[serde(default)]
    last_projection_stats: Option<ProjectionStats>,
    #[serde(default)]
    last_compact_reason: Option<String>,
    #[serde(default)]
    last_recovery_result: Option<String>,
    #[serde(default)]
    last_post_compact_validation: Option<PostCompactValidation>,
    #[serde(default)]
    committed_collapses: Vec<CollapseCommit>,
    #[serde(default)]
    staged_collapses: Vec<CollapseSnapshot>,
    #[serde(default)]
    session_memory: Option<SessionMemoryState>,
    #[serde(default)]
    snip_removals: Vec<SnipRemovalState>,
    #[serde(default)]
    microcompactions: Vec<MicrocompactState>,
    #[serde(default)]
    preserved_segment: Option<PreservedSegmentMetadata>,
    #[serde(default)]
    compact_boundary: Option<CompactBoundaryMetadata>,
}

impl<'de> Deserialize<'de> for ContextRuntimeState {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let wire = LegacyContextRuntimeStateWire::deserialize(deserializer)?;
        let mut store = wire.store.unwrap_or_default();

        if store.collapse_commits.is_empty() {
            store.collapse_commits = wire.committed_collapses;
        }
        if store.staged_snapshot.is_none() {
            store.staged_snapshot = wire.staged_collapses.into_iter().last();
        }
        if store.session_memory.is_none() {
            store.session_memory = wire.session_memory;
        }
        if store.snip_entries.is_empty() {
            store.snip_entries = wire.snip_removals;
        }
        if store.microcompact_entries.is_empty() {
            store.microcompact_entries = wire.microcompactions;
        }
        if store.preserved_segment.is_none() {
            store.preserved_segment = wire.preserved_segment;
        }
        if store.boundary.is_none() {
            store.boundary = wire.compact_boundary;
        }
        if !store.entry_log.is_empty() {
            merge_missing_structural_entries_into_entry_log(&mut store);
        }
        store = store.with_backfilled_entry_log();
        if !store.entry_log.is_empty() {
            store = rebuild_store_from_entry_log(store);
        }

        Ok(Self {
            schema_version: wire
                .schema_version
                .unwrap_or(CURRENT_CONTEXT_RUNTIME_SCHEMA_VERSION)
                .max(CURRENT_CONTEXT_RUNTIME_SCHEMA_VERSION),
            store,
            runtime_compactions: wire.runtime_compactions,
            last_projection_stats: wire.last_projection_stats,
            last_compact_reason: wire.last_compact_reason,
            last_recovery_result: wire.last_recovery_result,
            last_post_compact_validation: wire.last_post_compact_validation,
        })
    }
}

fn merge_missing_structural_entries_into_entry_log(store: &mut ContextRuntimeStore) {
    let replayed = rebuild_store_from_entry_log(store.clone());

    if !entry_log_mentions_staged_snapshot(&store.entry_log) && replayed.staged_snapshot.is_none() {
        if let Some(snapshot) = store.staged_snapshot.clone() {
            store
                .entry_log
                .push(ContextRuntimeStoreEntry::StagedSnapshotSet { snapshot });
        }
    }

    if !entry_log_mentions_collapse_commits(&store.entry_log)
        && replayed.collapse_commits.is_empty()
        && !store.collapse_commits.is_empty()
    {
        for commit in store.collapse_commits.clone() {
            store
                .entry_log
                .push(ContextRuntimeStoreEntry::CollapseCommitAdded { commit });
        }
    }

    if !entry_log_mentions_session_memory(&store.entry_log) && replayed.session_memory.is_none() {
        if let Some(session_memory) = store.session_memory.clone() {
            store
                .entry_log
                .push(ContextRuntimeStoreEntry::SessionMemorySet { session_memory });
        }
    }
}

fn entry_log_mentions_staged_snapshot(entries: &[ContextRuntimeStoreEntry]) -> bool {
    entries.iter().any(|entry| {
        matches!(
            entry,
            ContextRuntimeStoreEntry::StagedSnapshotSet { .. }
                | ContextRuntimeStoreEntry::StagedSnapshotCleared
        )
    })
}

fn entry_log_mentions_collapse_commits(entries: &[ContextRuntimeStoreEntry]) -> bool {
    entries.iter().any(|entry| {
        matches!(
            entry,
            ContextRuntimeStoreEntry::CollapseCommitAdded { .. }
                | ContextRuntimeStoreEntry::CollapseCommitsCleared
        )
    })
}

fn entry_log_mentions_session_memory(entries: &[ContextRuntimeStoreEntry]) -> bool {
    entries.iter().any(|entry| {
        matches!(
            entry,
            ContextRuntimeStoreEntry::SessionMemorySet { .. }
                | ContextRuntimeStoreEntry::SessionMemoryCleared
        )
    })
}

fn entry_log_mentions_boundary(entries: &[ContextRuntimeStoreEntry]) -> bool {
    entries.iter().any(|entry| {
        matches!(
            entry,
            ContextRuntimeStoreEntry::BoundarySet { .. }
                | ContextRuntimeStoreEntry::BoundaryCleared
        )
    })
}

fn entry_log_mentions_preserved_segment(entries: &[ContextRuntimeStoreEntry]) -> bool {
    entries.iter().any(|entry| {
        matches!(
            entry,
            ContextRuntimeStoreEntry::PreservedSegmentSet { .. }
                | ContextRuntimeStoreEntry::PreservedSegmentCleared
        )
    })
}

impl ExtensionState for ContextRuntimeState {
    const EXTENSION_NAME: &'static str = "context_runtime";
    const VERSION: &'static str = "v0";
}

impl ContextRuntimeState {
    pub fn restored_from_entry_log(&self) -> Self {
        let mut next = self.clone();
        next.store = next
            .store
            .with_backfilled_entry_log()
            .restored_from_entries();
        next
    }

    pub fn append_collapse_commit(&mut self, commit: CollapseCommit) {
        self.store.append_collapse_commit(commit);
    }

    pub fn clear_committed_collapses(&mut self) {
        self.store.clear_committed_collapses();
    }

    pub fn committed_collapses(&self) -> &[CollapseCommit] {
        &self.store.collapse_commits
    }

    #[cfg(test)]
    pub fn committed_collapses_mut(&mut self) -> &mut Vec<CollapseCommit> {
        &mut self.store.collapse_commits
    }

    pub fn staged_snapshot(&self) -> Option<&CollapseSnapshot> {
        self.store.staged_snapshot.as_ref()
    }

    #[cfg(test)]
    pub fn staged_snapshot_mut(&mut self) -> Option<&mut CollapseSnapshot> {
        self.store.staged_snapshot.as_mut()
    }

    pub fn staged_collapse_count(&self) -> usize {
        usize::from(self.store.staged_snapshot.is_some())
    }

    #[cfg(test)]
    pub fn take_staged_snapshot(&mut self) -> Option<CollapseSnapshot> {
        self.store.staged_snapshot.take()
    }

    pub fn set_staged_snapshot(&mut self, snapshot: Option<CollapseSnapshot>) {
        self.store.set_staged_snapshot(snapshot);
    }

    pub fn session_memory(&self) -> Option<&SessionMemoryState> {
        self.store.session_memory.as_ref()
    }

    #[cfg(test)]
    pub fn session_memory_mut(&mut self) -> Option<&mut SessionMemoryState> {
        self.store.session_memory.as_mut()
    }

    pub fn set_session_memory(&mut self, session_memory: Option<SessionMemoryState>) {
        self.store.set_session_memory(session_memory);
    }

    pub fn snip_entries(&self) -> &[SnipRemovalState] {
        &self.store.snip_entries
    }

    pub fn set_snip_entries(&mut self, entries: Vec<SnipRemovalState>) {
        self.store.set_snip_entries(entries);
    }

    #[cfg(test)]
    pub fn snip_entries_mut(&mut self) -> &mut Vec<SnipRemovalState> {
        &mut self.store.snip_entries
    }

    pub fn microcompact_entries(&self) -> &[MicrocompactState] {
        &self.store.microcompact_entries
    }

    pub fn set_microcompact_entries(&mut self, entries: Vec<MicrocompactState>) {
        self.store.set_microcompact_entries(entries);
    }

    #[cfg(test)]
    pub fn microcompact_entries_mut(&mut self) -> &mut Vec<MicrocompactState> {
        &mut self.store.microcompact_entries
    }

    pub fn preserved_segment(&self) -> Option<&PreservedSegmentMetadata> {
        self.store.preserved_segment.as_ref()
    }

    #[cfg(test)]
    pub fn preserved_segment_mut(&mut self) -> Option<&mut PreservedSegmentMetadata> {
        self.store.preserved_segment.as_mut()
    }

    pub fn set_preserved_segment(&mut self, preserved_segment: Option<PreservedSegmentMetadata>) {
        self.store.set_preserved_segment(preserved_segment);
    }

    pub fn compact_boundary(&self) -> Option<&CompactBoundaryMetadata> {
        self.store.boundary.as_ref()
    }

    #[cfg(test)]
    pub fn compact_boundary_mut(&mut self) -> Option<&mut CompactBoundaryMetadata> {
        self.store.boundary.as_mut()
    }

    pub fn set_compact_boundary(&mut self, boundary: Option<CompactBoundaryMetadata>) {
        self.store.set_boundary(boundary);
    }

    pub fn clear_projection_entries(&mut self) {
        self.store.clear_projection_entries();
    }
}

pub(crate) fn rebuild_store_from_entry_log(store: ContextRuntimeStore) -> ContextRuntimeStore {
    let entry_log = store.entry_log.clone();
    let mut rebuilt = ContextRuntimeStore {
        entry_log,
        collapse_commits: Vec::new(),
        staged_snapshot: None,
        session_memory: None,
        snip_entries: Vec::new(),
        microcompact_entries: Vec::new(),
        preserved_segment: None,
        boundary: None,
    };

    for entry in rebuilt.entry_log.clone() {
        match entry {
            ContextRuntimeStoreEntry::StagedSnapshotSet { snapshot } => {
                rebuilt.staged_snapshot = Some(snapshot);
            }
            ContextRuntimeStoreEntry::StagedSnapshotCleared => {
                rebuilt.staged_snapshot = None;
            }
            ContextRuntimeStoreEntry::CollapseCommitAdded { commit } => {
                rebuilt.collapse_commits.push(commit);
            }
            ContextRuntimeStoreEntry::CollapseCommitsCleared => {
                rebuilt.collapse_commits.clear();
            }
            ContextRuntimeStoreEntry::SessionMemorySet { session_memory } => {
                rebuilt.session_memory = Some(session_memory);
            }
            ContextRuntimeStoreEntry::SessionMemoryCleared => {
                rebuilt.session_memory = None;
            }
            ContextRuntimeStoreEntry::SnipEntriesSet { entries } => {
                rebuilt.snip_entries = entries;
            }
            ContextRuntimeStoreEntry::SnipEntriesCleared => {
                rebuilt.snip_entries.clear();
            }
            ContextRuntimeStoreEntry::MicrocompactEntriesSet { entries } => {
                rebuilt.microcompact_entries = entries;
            }
            ContextRuntimeStoreEntry::MicrocompactEntriesCleared => {
                rebuilt.microcompact_entries.clear();
            }
            ContextRuntimeStoreEntry::BoundarySet { boundary } => {
                rebuilt.boundary = Some(boundary);
            }
            ContextRuntimeStoreEntry::BoundaryCleared => {
                rebuilt.boundary = None;
            }
            ContextRuntimeStoreEntry::PreservedSegmentSet { preserved_segment } => {
                rebuilt.preserved_segment = Some(preserved_segment);
            }
            ContextRuntimeStoreEntry::PreservedSegmentCleared => {
                rebuilt.preserved_segment = None;
            }
        }
    }

    if !entry_log_mentions_boundary(&rebuilt.entry_log) {
        rebuilt.boundary = store.boundary;
    }
    if !entry_log_mentions_preserved_segment(&rebuilt.entry_log) {
        rebuilt.preserved_segment = store.preserved_segment;
    }

    rebuilt.normalize_active_collapse_direction();

    rebuilt
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContextRuntimeAdvanceKind {
    Noop,
    ProjectionRefresh,
    StagedCollapse,
    CommittedCollapse,
    SessionMemoryCompaction,
}

#[derive(Debug, Clone)]
pub struct ContextRuntimeAdvance {
    pub kind: ContextRuntimeAdvanceKind,
    pub usage_ratio: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ContextRuntimeRecoveryKind {
    Noop,
    StagedCollapseCommitted,
    SessionMemoryCompaction,
}

#[derive(Debug, Clone)]
pub struct ContextRuntimeRecovery {
    pub kind: ContextRuntimeRecoveryKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum SessionMemoryPolicyKind {
    Auto,
    Manual,
    Overflow,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct SessionMemoryPolicy {
    pub min_tokens: usize,
    pub min_text_messages: usize,
    pub max_tokens: usize,
}

impl SessionMemoryPolicy {
    pub(crate) fn for_kind(kind: SessionMemoryPolicyKind) -> Self {
        match kind {
            SessionMemoryPolicyKind::Auto => Self {
                min_tokens: AUTO_SESSION_MEMORY_MIN_TOKENS,
                min_text_messages: AUTO_SESSION_MEMORY_MIN_TEXT_MESSAGES,
                max_tokens: AUTO_SESSION_MEMORY_MAX_TOKENS,
            },
            SessionMemoryPolicyKind::Manual => Self {
                min_tokens: MANUAL_SESSION_MEMORY_MIN_TOKENS,
                min_text_messages: MANUAL_SESSION_MEMORY_MIN_TEXT_MESSAGES,
                max_tokens: MANUAL_SESSION_MEMORY_MAX_TOKENS,
            },
            SessionMemoryPolicyKind::Overflow => Self {
                min_tokens: OVERFLOW_SESSION_MEMORY_MIN_TOKENS,
                min_text_messages: OVERFLOW_SESSION_MEMORY_MIN_TEXT_MESSAGES,
                max_tokens: OVERFLOW_SESSION_MEMORY_MAX_TOKENS,
            },
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct RuntimeBudget {
    pub context_limit: usize,
    pub effective_context_limit: usize,
    pub projected_tokens: usize,
    pub output_reserve_tokens: usize,
    pub auto_compact_threshold: f64,
}

impl RuntimeBudget {
    pub(crate) fn new(
        context_limit: usize,
        projected_tokens: usize,
        output_reserve_tokens: usize,
        auto_compact_threshold: f64,
    ) -> Self {
        let effective_context_limit = context_limit.saturating_sub(output_reserve_tokens);
        Self {
            context_limit: context_limit.max(1),
            effective_context_limit: effective_context_limit.max(1),
            projected_tokens,
            output_reserve_tokens,
            auto_compact_threshold,
        }
    }

    pub(crate) fn usage_ratio(self) -> f64 {
        self.projected_tokens as f64 / self.context_limit as f64
    }

    pub(crate) fn effective_usage_ratio(self) -> f64 {
        self.projected_tokens as f64 / self.effective_context_limit as f64
    }

    pub(crate) fn remaining_headroom(self) -> usize {
        self.effective_context_limit
            .saturating_sub(self.projected_tokens)
    }

    pub(crate) fn auto_compact_threshold_tokens(self, threshold_override: Option<f64>) -> usize {
        let ratio_threshold = threshold_override.unwrap_or(self.auto_compact_threshold);
        let ratio_tokens = (self.context_limit as f64 * ratio_threshold)
            .round()
            .clamp(0.0, self.context_limit as f64) as usize;
        let headroom_tokens = self
            .effective_context_limit
            .saturating_sub(AUTO_HEADROOM_BUFFER_TOKENS);
        ratio_tokens.min(headroom_tokens)
    }

    pub(crate) fn should_commit_staged_collapse(self) -> bool {
        self.projected_tokens >= COMMIT_ABSOLUTE_TRIGGER_TOKENS
            || self.remaining_headroom() <= COMMIT_HEADROOM_BUFFER_TOKENS
    }

    pub(crate) fn should_auto_session_memory(self, threshold_override: Option<f64>) -> bool {
        self.projected_tokens >= AUTO_ABSOLUTE_TRIGGER_TOKENS
            || self.remaining_headroom() <= AUTO_HEADROOM_BUFFER_TOKENS
            || self.projected_tokens >= self.auto_compact_threshold_tokens(threshold_override)
    }

    pub(crate) fn should_stage(self) -> bool {
        self.projected_tokens >= STAGE_ABSOLUTE_TRIGGER_TOKENS
            || self.remaining_headroom() <= STAGE_HEADROOM_BUFFER_TOKENS
            || self.effective_usage_ratio() >= DEFAULT_STAGE_THRESHOLD
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deserializing_v5_state_upgrades_store_and_schema_to_current() {
        let raw = serde_json::json!({
            "schemaVersion": 5,
            "store": {
                "entryLog": [
                    { "kind": "snipEntriesCleared" },
                    { "kind": "microcompactEntriesCleared" }
                ],
                "collapseCommits": [],
                "snipEntries": [],
                "microcompactEntries": []
            },
            "runtimeCompactions": 1,
            "lastCompactReason": "manual_session_memory"
        });

        let state: ContextRuntimeState =
            serde_json::from_value(raw).expect("deserialize runtime state");
        assert_eq!(state.schema_version, CURRENT_CONTEXT_RUNTIME_SCHEMA_VERSION);
        assert_eq!(state.store.entry_log.len(), 2);
        assert_eq!(
            ContextRuntimeState::default().schema_version,
            CURRENT_CONTEXT_RUNTIME_SCHEMA_VERSION
        );
        assert_eq!(
            state.last_compact_reason.as_deref(),
            Some("manual_session_memory")
        );
    }

    #[test]
    fn deserializing_legacy_live_store_backfills_entry_log() {
        let raw = serde_json::json!({
            "schemaVersion": 5,
            "committedCollapses": [
                {
                    "commitId": "legacy-commit",
                    "summary": "legacy",
                    "startIndex": 1,
                    "endIndex": 3,
                    "direction": "up_to",
                    "createdAt": 1
                }
            ]
        });

        let state: ContextRuntimeState =
            serde_json::from_value(raw).expect("deserialize legacy runtime state");

        assert_eq!(state.store.entry_log.len(), 1);
        assert_eq!(state.committed_collapses().len(), 1);
        assert_eq!(state.committed_collapses()[0].summary, "legacy");
    }

    #[test]
    fn deserializing_partial_entry_log_keeps_legacy_structural_state() {
        let raw = serde_json::json!({
            "schemaVersion": 5,
            "store": {
                "entryLog": [
                    { "kind": "snipEntriesCleared" }
                ],
                "collapseCommits": [],
                "snipEntries": []
            },
            "committedCollapses": [
                {
                    "commitId": "legacy-commit",
                    "summary": "legacy",
                    "startIndex": 1,
                    "endIndex": 3,
                    "direction": "up_to",
                    "createdAt": 1
                }
            ]
        });

        let state: ContextRuntimeState =
            serde_json::from_value(raw).expect("deserialize mixed runtime state");

        assert_eq!(state.committed_collapses().len(), 1);
        assert_eq!(state.committed_collapses()[0].summary, "legacy");
        assert!(state.store.entry_log.len() >= 2);
    }

    #[test]
    fn deserializing_partial_entry_log_does_not_restore_legacy_projection_fields() {
        let raw = serde_json::json!({
            "schemaVersion": 5,
            "store": {
                "entryLog": [
                    { "kind": "snipEntriesCleared" },
                    { "kind": "microcompactEntriesCleared" }
                ],
                "snipEntries": [],
                "microcompactEntries": []
            },
            "snipRemovals": [
                {
                    "removedIndexes": [1],
                    "removedMessageIds": ["m2"],
                    "removedCount": 1,
                    "tokenEstimateFreed": 50,
                    "reason": "legacy",
                    "createdAt": 1
                }
            ],
            "microcompactions": [
                {
                    "messageIndex": 2,
                    "messageId": "m3",
                    "toolResponseIds": ["tool-1"],
                    "mode": "cached",
                    "originalTextChars": 100,
                    "originalTextLines": 4,
                    "compactedTextChars": 20,
                    "compactedAt": 2
                }
            ]
        });

        let state: ContextRuntimeState =
            serde_json::from_value(raw).expect("deserialize mixed runtime state");

        assert!(state.snip_entries().is_empty());
        assert!(state.microcompact_entries().is_empty());
        assert_eq!(state.store.entry_log.len(), 2);
    }

    #[test]
    fn deserializing_partial_entry_log_keeps_legacy_session_memory_boundary_and_segment() {
        let raw = serde_json::json!({
            "schemaVersion": 5,
            "store": {
                "entryLog": [
                    { "kind": "snipEntriesCleared" }
                ],
                "snipEntries": []
            },
            "sessionMemory": {
                "summary": "legacy-memory",
                "preservedStartIndex": 3,
                "preservedEndIndex": 5,
                "preservedMessageCount": 3,
                "preservedTokenEstimate": 120,
                "tailAnchorIndex": 5,
                "updatedAt": 1
            },
            "compactBoundary": {
                "anchorIndex": 3,
                "headIndex": 3,
                "tailIndex": 5,
                "direction": "up_to",
                "createdAt": 1
            },
            "preservedSegment": {
                "startIndex": 3,
                "endIndex": 5,
                "tailAnchorIndex": 5,
                "reason": "legacy-boundary"
            }
        });

        let state: ContextRuntimeState =
            serde_json::from_value(raw).expect("deserialize mixed runtime state");

        assert_eq!(
            state.session_memory().map(|memory| memory.summary.as_str()),
            Some("legacy-memory")
        );
        assert_eq!(
            state.compact_boundary().map(|boundary| boundary.tail_index),
            Some(5)
        );
        assert_eq!(
            state
                .preserved_segment()
                .map(|segment| segment.reason.as_str()),
            Some("legacy-boundary")
        );
        assert_eq!(state.store.entry_log.len(), 2);
    }

    #[test]
    fn deserializing_partial_entry_log_prefers_existing_structural_entries_over_conflicting_legacy()
    {
        let raw = serde_json::json!({
            "schemaVersion": 5,
            "store": {
                "entryLog": [
                    {
                        "kind": "sessionMemorySet",
                        "sessionMemory": {
                            "summary": "from-entry-log",
                            "preservedStartIndex": 2,
                            "preservedEndIndex": 4,
                            "preservedMessageCount": 3,
                            "preservedTokenEstimate": 90,
                            "tailAnchorIndex": 4,
                            "updatedAt": 1
                        }
                    }
                ],
                "sessionMemory": {
                    "summary": "from-store-live",
                    "preservedStartIndex": 7,
                    "preservedEndIndex": 9,
                    "preservedMessageCount": 3,
                    "preservedTokenEstimate": 200,
                    "tailAnchorIndex": 9,
                    "updatedAt": 2
                }
            },
            "sessionMemory": {
                "summary": "from-legacy-top-level",
                "preservedStartIndex": 11,
                "preservedEndIndex": 13,
                "preservedMessageCount": 3,
                "preservedTokenEstimate": 300,
                "tailAnchorIndex": 13,
                "updatedAt": 3
            }
        });

        let state: ContextRuntimeState =
            serde_json::from_value(raw).expect("deserialize mixed runtime state");

        assert_eq!(
            state.session_memory().map(|memory| memory.summary.as_str()),
            Some("from-entry-log")
        );
        assert_eq!(state.store.entry_log.len(), 1);
    }

    #[test]
    fn deserializing_partial_entry_log_respects_explicit_session_memory_clear() {
        let raw = serde_json::json!({
            "schemaVersion": 5,
            "store": {
                "entryLog": [
                    { "kind": "sessionMemoryCleared" }
                ]
            },
            "sessionMemory": {
                "summary": "legacy-top-level",
                "preservedStartIndex": 3,
                "preservedEndIndex": 5,
                "preservedMessageCount": 3,
                "preservedTokenEstimate": 120,
                "tailAnchorIndex": 5,
                "updatedAt": 1
            }
        });

        let state: ContextRuntimeState =
            serde_json::from_value(raw).expect("deserialize mixed runtime state");

        assert!(state.session_memory().is_none());
        assert_eq!(state.store.entry_log.len(), 1);
    }

    #[test]
    fn deserializing_partial_entry_log_respects_explicit_collapse_clear() {
        let raw = serde_json::json!({
            "schemaVersion": 5,
            "store": {
                "entryLog": [
                    { "kind": "collapseCommitsCleared" }
                ]
            },
            "committedCollapses": [
                {
                    "commitId": "legacy-commit",
                    "summary": "legacy",
                    "startIndex": 1,
                    "endIndex": 3,
                    "direction": "up_to",
                    "createdAt": 1
                }
            ]
        });

        let state: ContextRuntimeState =
            serde_json::from_value(raw).expect("deserialize mixed runtime state");

        assert!(state.committed_collapses().is_empty());
        assert_eq!(state.store.entry_log.len(), 1);
    }

    #[test]
    fn serializing_state_restores_entry_log_before_emitting_store() {
        let mut state = ContextRuntimeState::default();
        state.append_collapse_commit(CollapseCommit {
            commit_id: Some("commit-serialize".to_string()),
            summary: "persisted".to_string(),
            start_index: 1,
            end_index: 3,
            direction: CompactDirection::UpTo,
            start_message_id: None,
            end_message_id: None,
            created_at: 1,
        });
        state.committed_collapses_mut().clear();

        let value = serde_json::to_value(&state).expect("serialize runtime state");
        let commits = value
            .get("store")
            .and_then(|store| store.get("collapseCommits"))
            .and_then(|commits| commits.as_array())
            .expect("serialized collapse commits");

        assert_eq!(commits.len(), 1);
        assert_eq!(
            commits[0].get("summary").and_then(|value| value.as_str()),
            Some("persisted")
        );
    }

    #[test]
    fn serializing_state_upgrades_schema_version_to_current() {
        let state = ContextRuntimeState {
            schema_version: 5,
            ..ContextRuntimeState::default()
        };

        let value = serde_json::to_value(&state).expect("serialize runtime state");
        assert_eq!(
            value.get("schemaVersion").and_then(|value| value.as_u64()),
            Some(CURRENT_CONTEXT_RUNTIME_SCHEMA_VERSION as u64)
        );
    }

    #[test]
    fn restored_from_entry_log_preserves_cached_boundary_and_segment_without_log_entries() {
        let mut state = ContextRuntimeState::default();
        state.set_session_memory(Some(SessionMemoryState {
            summary: "memory".to_string(),
            summarized_through_message_id: None,
            preserved_start_index: 2,
            preserved_end_index: 3,
            preserved_start_message_id: None,
            preserved_end_message_id: None,
            preserved_message_count: 2,
            preserved_token_estimate: 10,
            tail_anchor_index: 3,
            tail_anchor_message_id: None,
            updated_at: 1,
        }));
        state.set_compact_boundary(Some(CompactBoundaryMetadata {
            anchor_index: 2,
            head_index: 2,
            tail_index: 3,
            direction: CompactDirection::UpTo,
            anchor_message_id: None,
            head_message_id: None,
            tail_message_id: None,
            created_at: 1,
        }));
        state.set_preserved_segment(Some(PreservedSegmentMetadata {
            start_index: 2,
            end_index: 3,
            tail_anchor_index: 3,
            start_message_id: None,
            end_message_id: None,
            tail_anchor_message_id: None,
            reason: "cached-boundary".to_string(),
        }));

        let restored = state.restored_from_entry_log();

        assert_eq!(
            restored
                .compact_boundary()
                .map(|boundary| boundary.tail_index),
            Some(3)
        );
        assert_eq!(
            restored
                .preserved_segment()
                .map(|segment| segment.reason.as_str()),
            Some("cached-boundary")
        );
        assert_eq!(restored.store.entry_log.len(), 1);
    }

    #[test]
    fn serializing_state_does_not_promote_cached_boundary_and_segment_into_entry_log() {
        let mut state = ContextRuntimeState::default();
        state.set_session_memory(Some(SessionMemoryState {
            summary: "memory".to_string(),
            summarized_through_message_id: None,
            preserved_start_index: 2,
            preserved_end_index: 3,
            preserved_start_message_id: None,
            preserved_end_message_id: None,
            preserved_message_count: 2,
            preserved_token_estimate: 10,
            tail_anchor_index: 3,
            tail_anchor_message_id: None,
            updated_at: 1,
        }));
        state.set_compact_boundary(Some(CompactBoundaryMetadata {
            anchor_index: 2,
            head_index: 2,
            tail_index: 3,
            direction: CompactDirection::UpTo,
            anchor_message_id: None,
            head_message_id: None,
            tail_message_id: None,
            created_at: 1,
        }));
        state.set_preserved_segment(Some(PreservedSegmentMetadata {
            start_index: 2,
            end_index: 3,
            tail_anchor_index: 3,
            start_message_id: None,
            end_message_id: None,
            tail_anchor_message_id: None,
            reason: "cached-boundary".to_string(),
        }));

        let value = serde_json::to_value(&state).expect("serialize runtime state");
        let entry_log = value["store"]["entryLog"].as_array().expect("entry log");
        assert_eq!(entry_log.len(), 1);
        assert_eq!(entry_log[0]["kind"].as_str(), Some("sessionMemorySet"));
        assert_eq!(value["store"]["boundary"]["tailIndex"].as_u64(), Some(3));
        assert_eq!(
            value["store"]["preservedSegment"]["reason"].as_str(),
            Some("cached-boundary")
        );
    }

    #[test]
    fn serializing_legacy_live_store_backfills_entry_log() {
        let state = ContextRuntimeState {
            store: ContextRuntimeStore {
                entry_log: Vec::new(),
                collapse_commits: vec![CollapseCommit {
                    commit_id: Some("legacy-commit".to_string()),
                    summary: "legacy".to_string(),
                    start_index: 1,
                    end_index: 3,
                    direction: CompactDirection::UpTo,
                    start_message_id: None,
                    end_message_id: None,
                    created_at: 1,
                }],
                ..ContextRuntimeStore::default()
            },
            ..ContextRuntimeState::default()
        };

        let value = serde_json::to_value(&state).expect("serialize runtime state");
        let entry_log = value
            .get("store")
            .and_then(|store| store.get("entryLog"))
            .and_then(|entry_log| entry_log.as_array())
            .expect("serialized entry log");

        assert_eq!(entry_log.len(), 1);
        assert_eq!(
            entry_log[0].get("kind").and_then(|value| value.as_str()),
            Some("collapseCommitAdded")
        );
    }

    #[test]
    fn restored_from_entry_log_normalizes_mixed_collapse_directions() {
        let mut state = ContextRuntimeState::default();
        state.append_collapse_commit(CollapseCommit {
            commit_id: Some("commit-up".to_string()),
            summary: "up".to_string(),
            start_index: 0,
            end_index: 3,
            direction: CompactDirection::UpTo,
            start_message_id: Some("m1".to_string()),
            end_message_id: Some("m3".to_string()),
            created_at: 1,
        });
        state.append_collapse_commit(CollapseCommit {
            commit_id: Some("commit-from".to_string()),
            summary: "from".to_string(),
            start_index: 6,
            end_index: 8,
            direction: CompactDirection::From,
            start_message_id: Some("m7".to_string()),
            end_message_id: Some("m8".to_string()),
            created_at: 2,
        });
        state.set_compact_boundary(Some(CompactBoundaryMetadata {
            anchor_index: 0,
            head_index: 0,
            tail_index: 3,
            direction: CompactDirection::UpTo,
            anchor_message_id: Some("m1".to_string()),
            head_message_id: Some("m1".to_string()),
            tail_message_id: Some("m4".to_string()),
            created_at: 2,
        }));

        let restored = state.restored_from_entry_log();

        assert_eq!(restored.committed_collapses().len(), 1);
        assert_eq!(
            restored.committed_collapses()[0].direction,
            CompactDirection::From
        );
        assert_eq!(restored.store.entry_log.len(), 1);
        assert_eq!(
            restored.store.entry_log[0],
            ContextRuntimeStoreEntry::CollapseCommitAdded {
                commit: restored.committed_collapses()[0].clone()
            }
        );
    }

    #[test]
    fn serializing_mixed_direction_store_emits_only_active_direction() {
        let mut state = ContextRuntimeState::default();
        state.append_collapse_commit(CollapseCommit {
            commit_id: Some("commit-up".to_string()),
            summary: "up".to_string(),
            start_index: 0,
            end_index: 3,
            direction: CompactDirection::UpTo,
            start_message_id: Some("m1".to_string()),
            end_message_id: Some("m3".to_string()),
            created_at: 1,
        });
        state.append_collapse_commit(CollapseCommit {
            commit_id: Some("commit-from".to_string()),
            summary: "from".to_string(),
            start_index: 6,
            end_index: 8,
            direction: CompactDirection::From,
            start_message_id: Some("m7".to_string()),
            end_message_id: Some("m8".to_string()),
            created_at: 2,
        });
        state.set_compact_boundary(Some(CompactBoundaryMetadata {
            anchor_index: 0,
            head_index: 0,
            tail_index: 3,
            direction: CompactDirection::UpTo,
            anchor_message_id: Some("m1".to_string()),
            head_message_id: Some("m1".to_string()),
            tail_message_id: Some("m4".to_string()),
            created_at: 2,
        }));

        let value = serde_json::to_value(&state).expect("serialize runtime state");
        let commits = value["store"]["collapseCommits"]
            .as_array()
            .expect("serialized collapse commits");
        let entry_log = value["store"]["entryLog"]
            .as_array()
            .expect("serialized entry log");

        assert_eq!(commits.len(), 1);
        assert_eq!(commits[0]["direction"].as_str(), Some("from"));
        assert_eq!(entry_log.len(), 1);
        assert_eq!(entry_log[0]["commit"]["direction"].as_str(), Some("from"));
    }
}
